### ISSUE TITLE
Can't install based on dependencies

### ISSUE THREAD

**Issue by ericbrownaustin** [abilian/olapy#13]
I am trying to install, but console returns error `xmla 0.7.2 has requirement requests==1.2.3, but you'll have requests 2.18.4 which is incompatible`, however, there seems to be some dependencies in olapy that rely on a newer version of requests.  Is there a way around this?

**Comment by sfermigier** [comment]
Can you be more specific in which version of Python you're using, on which platform, and maybe provide some logs from your install attemps ?

Here's some on my Mac (works good on Linux too, see https://travis-ci.org/abilian/olapy/builds ):

```
➜  ~ which python
/Users/fermigier/envs/tmp/bin/python
➜  ~ python --version
Python 2.7.14
➜  ~ pip install olapy
[...]
Successfully installed SQLAlchemy-1.1.18 Unidecode-0.4.21 appdirs-1.4.3 attrs-17.4.0 awesome-slugify-1.6.5 bonobo-0.5.2 bonobo-sqlalchemy-0.5.1 certifi-2018.4.16 colorama-0.3.9 enum34-1.1.6 fs-2.0.20 idna-2.6 olapy-0.6.2 packaging-16.8 pbr-4.0.2 psutil-5.4.5 pyparsing-2.2.0 python-dotenv-0.8.2 regex-2018.2.21 requests-2.18.4 spyne-2.12.14 stevedore-1.28.0 urllib3-1.22 xmlwitch-0.3
You are using pip version 9.0.3, however version 10.0.1 is available.
```
